// Automatically generated by ck_pylib
 // ver1.0.1 author:zxl 
#ifndef __CK_CONFIG_H__
#define __CK_CONFIG_H__

#define ROOT_PATH "../../"
#define PRO_PATH "./"
#define PRO_NAME "lr_project"

#endif // __CK_CONFIG_H__