/* Automatically generated by ck_version.py */
/* author:zxl ver:2.0.0 */
#ifndef __CK_VERSION_H__
#define __CK_VERSION_H__

#define CK_SOFTWARE_VERSION "2.1.5"
#define CK_SOFTWARE_BUILD_TIME "2025-07-25 15:26:35"
#define CK_SOFTWARE_COMMIT_HASH "31858ef"


#endif // __CK_VERSION_H__