# Author: zhuxuanlin
# Email: xuanlinzhu@qq.com
# Date: 2025-6-29

# Description: This file is used to create a quick template project for CMake.

import os

# Script version
ck_config_gen_version = "2.0.0"


def parse_config_file_cmake(config_file):
    config_vars = {}
    with open(config_file, "r") as f:
        for line in f:
            if line.startswith("#") or line.strip() == "":
                continue
            key, value = line.strip().split("=", 1)
            key = key[7:] if key.startswith("CONFIG_") else key
            if value.startswith('"') and value.endswith('"'):
                value = value[1:-1]
            config_vars[key] = value
    return config_vars


def write_cmake_file(config_vars, cmake_file):
    with open(cmake_file, "w") as f:
        f.write("# Automatically generated by ck_config_gen\n# author:zxl ver:" + ck_config_gen_version + "\n")
        for key, value in config_vars.items():
            f.write('set({} "{}")\n'.format(key, value))


def convert_config_to_cmake(config_file, cmake_file):
    config_vars = parse_config_file_cmake(config_file)
    write_cmake_file(config_vars, cmake_file)


def parse_config_file_header(config_file):
    config_vars = []
    with open(config_file, "r") as f:
        for line in f:
            if line.startswith("#") or line.strip() == "":
                continue
            key, value = line.strip().split("=", 1)
            value = value.strip()
            if value == "y":
                value = "1"
            key = key[7:] if key.startswith("CONFIG_") else key
            config_vars.append((key, value))
    return config_vars


def write_config_header(config_vars, header_file):
    import re

    config_dict = {k: v for k, v in config_vars}
    version_enabled = str(config_dict.get("CK_VERSION_ENABLE", "0")).strip().lower() not in {
        "",
        "n",
        "false",
        "0",
        "off",
    }

    fixed_macros = {
        "CK_SOFTWARE_VERSION": '"0.0.1"',
        "CK_SOFTWARE_BUILD_TIME": '"1970-01-01 00:00:00"',
        "CK_SOFTWARE_COMMIT_HASH": '"0000000"',
    }

    existing_macros = {}
    if version_enabled and os.path.exists(header_file):
        with open(header_file, "r") as f:
            for line in f:
                for macro in fixed_macros:
                    m = re.match(r"#define\s+" + macro + r'\s+"(.+)"', line)
                    if m:
                        existing_macros[macro] = f'"{m.group(1)}"'

    if version_enabled:
        for macro in fixed_macros:
            if macro in existing_macros:
                fixed_macros[macro] = existing_macros[macro]
        config_dict.update(fixed_macros)
    else:
        for macro in fixed_macros:
            config_dict.pop(macro, None)

    with open(header_file, "w") as f:
        f.write("/* Automatically generated by ck_config_gen */\n")
        f.write("/* author:zxl ver:" + ck_config_gen_version + " */\n")
        f.write("#ifndef __CK_CONFIG_H__\n#define __CK_CONFIG_H__\n\n")

        for key, value in sorted(config_dict.items()):
            f.write(f"#define {key} {value}\n")

        f.write("\n#endif // __CK_CONFIG_H__\n")


def convert_config_to_header(config_file, header_file):
    config_vars = parse_config_file_header(config_file)
    write_config_header(config_vars, header_file)


config_file = ".config"
cmake_file = "ck_config.cmake"
header_file = "ck_config.h"

convert_config_to_cmake(config_file, cmake_file)
convert_config_to_header(config_file, header_file)
