/* Automatically generated by ck_pylib */
/* author:zxl ver:2.0.0 */
#ifndef __CK_CONFIG_H__
#define __CK_CONFIG_H__

#define CK_SOFTWARE_BUILD_TIME "2026-02-07 17:22:46"
#define CK_SOFTWARE_COMMIT_HASH "7ef4ad3"
#define CK_SOFTWARE_VERSION "0.10.11"
#define CK_TOOLS_PATH "../../../"
#define DRV_DRV1 1
#define DRV_DRV1_NUM 0
#define PACK_PACK1 1
#define PACK_PACK1_STR "it's pack1"
#define PACK_UNITY_ENABLE 1
#define PACK_UNITY_EX_FIXTURE 1
#define PACK_UNITY_EX_MEMORY 1
#define PRO_NAME "template"
#define PRO_TEST_UNIT 1
#define PRO_TOP_PATH "../.."
#define TC_BUILD_TYPE_DEBUG 1
#define TC_COMPILE_OPTIONS "-lm -g -O0"
#define TC_CPU_X86_64 1
#define TC_CXX_STANDARD "11"
#define TC_C_CXX_COMPILER "/usr/bin/gcc"
#define TC_C_STANDARD "11"
#define TC_DEFINE_MACROS ""
#define TC_LIBRARY_DIRS "./"
#define TC_LINK_FILE ""
#define TC_LINK_LIBRARIES ""
#define TC_LINK_OPTIONS ""
#define TC_SYSTEM_NAME_WINDOWS 1

#endif // __CK_CONFIG_H__
