// Automatically generated by config_to_header.py
#ifndef __CK_CONFIG_H__
#define __CK_CONFIG_H__

#define CK_CONFIG "config1"
#define MOD1_ENABLE 1
#define MOD2_ENABLE 1
#define CK_WIN7 1
#define CK_STRING "string"
#define CK_MENUCONFIG 1
#define CK_MENUCONFIG1 32
#define CK_MENUCONFIG2 64

#endif // __CK_CONFIG_H__