# Automatically generated by config_to_cmake.py
set(CK_CONFIG "test1")
set(MOD1_ENABLE "y")
set(CK_WIN11 "y")
set(CK_STRING "string")
set(CK_MENUCONFIG "y")
set(CK_MENUCONFIG1 "32")
set(CK_MENUCONFIG2 "64")
