# Author: zhuxuanlin
# Email: xuanlinzhu@qq.com
# Date: 2024-3-26
# Version: 1.0
#
# Description: 这个文件用于创建cmake的快速模板工程
import os

def parse_config_file_cmake(config_file):
    config_vars = {}
    with open(config_file, 'r') as f:
        for line in f:
            # 跳过注释和空行
            if line.startswith('#') or line.strip() == '':
                continue
            # 解析配置行
            key, value = line.strip().split('=', 1)
            # 去除键名中的 CONFIG_ 前缀
            key = key[7:] if key.startswith('CONFIG_') else key
            # 处理值中的引号
            if value.startswith('"') and value.endswith('"'):
                value = value[1:-1]
            # 添加到字典中
            config_vars[key] = value
    return config_vars

def write_cmake_file(config_vars, cmake_file):
    with open(cmake_file, 'w') as f:
        f.write('# Automatically generated by config_to_cmake.py\n')
        for key, value in config_vars.items():
            f.write('set({} "{}")\n'.format(key, value))

def convert_config_to_cmake(config_file, cmake_file):
    config_vars = parse_config_file_cmake(config_file)
    write_cmake_file(config_vars, cmake_file)

def parse_config_file_header(config_file):
    config_vars = []
    with open(config_file, 'r') as f:
        for line in f:
            # 跳过注释和空行
            if line.startswith('#') or line.strip() == '':
                continue
            # 解析配置行
            key, value = line.strip().split('=', 1)
            # 如果值为 'y'，则替换为空格
            value = value.strip()
            if value == 'y':
                value = '1'
            # 去除键名中的 CONFIG_ 前缀
            key = key[7:] if key.startswith('CONFIG_') else key
            # 添加到列表中
            config_vars.append((key, value))
    return config_vars

def write_config_header(config_vars, header_file):
    with open(header_file, 'w') as f:
        f.write('// Automatically generated by config_to_header.py\n')
        for key, value in config_vars:
            f.write('#define {} {}\n'.format(key, value))

def convert_config_to_header(config_file, header_file):
    config_vars = parse_config_file_header(config_file)
    write_config_header(config_vars, header_file)

config_file = '.config'  # 您的.config文件的路径
cmake_file = 'ck_config.cmake'      # 生成的config.cmake文件的路径
header_file = 'ck_config.h'      # 生成的ck_config.h文件的路径
# 将.config文件转换为config.cmake文件
convert_config_to_cmake(config_file, cmake_file)
# 将.config文件转换为ck_config.h文件
convert_config_to_header(config_file, header_file)
