/* Automatically generated by ck_version.py */
/* author:zxl ver:2.0.0 */
#ifndef __CK_VERSION_H__
#define __CK_VERSION_H__

#define CK_SOFTWARE_VERSION "2.0.0"
#define CK_SOFTWARE_BUILD_TIME "2025-07-22 11:18:32"
#define CK_SOFTWARE_COMMIT_HASH "b0d3feb"


#endif // __CK_VERSION_H__